 CREATE TABLE IF NOT EXISTS users (    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
										first_name  VARCHAR(111),
										surname    VARCHAR(111),
										last_name   VARCHAR(111),
										birthday   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
										email   VARCHAR(111) NOT NULL,
										phone_number VARCHAR(111)
									);

CREATE TABLE IF NOT EXISTS photos (	id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									author_id  BIGINT REFERENCES users (id) ON DELETE CASCADE,
									link	   VARCHAR(111),
									description VARCHAR(111)
									);
                                        
                                       
